name: CI

# Run CI on pushes to main, pull requests into main, and version tags
on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ] # Trigger on semantic version tags like v1.0.0
  pull_request:
    branches: [ "main" ]

jobs:
  # Primary build and test job
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint code
        run: make lint # runs Ruff for style checks

      - name: Run tests
        run: make test # runs PyTest test suite

  # Conditional job to build and push Docker image on releases
  publish-image:
    # Only run if the workflow was triggered by a version tag push
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-and-test # ensure tests passed before image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (for multi-arch, optional)
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # ^^ Use GitHub Secrets for secure credentials

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/promptcastle:${{ github.ref_name }}
          # This will tag the image as e.g. user/promptcastle:v1.0.0 